#!/usr/bin/env python3
"""Who may read which secret.

A host may read a secret when (1) its tags (util/feat/cert/prop in
config/inventory/hosts.yml, through the tag manifests) need it, or you listed it
under extra_grants, and (2) its age public key is registered in config/access.yml.
`sync` writes .sops.yaml from that and re-encrypts every secret file to match.

  scripts/access.sh show
  scripts/access.sh add-admin <name> <age-public-key>
  scripts/access.sh add-host  <name> <age-public-key>     # key printed by bootstrap.sh
  scripts/access.sh remove-host <name>
  scripts/access.sh sync [--no-update] [--check]
"""
import glob
import importlib.util
import os
import re
import subprocess
import sys

try:
    import yaml
except ImportError:
    sys.exit("ERROR: PyYAML is required (it comes with Ansible: use the python3 that runs ansible)")

ROOT = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))
ACCESS = os.path.join(ROOT, "config", "access.yml")
HOSTS = os.path.join(ROOT, "config", "inventory", "hosts.yml")
SOPS_YAML = os.path.join(ROOT, ".sops.yaml")
HEADER = ("# Who may read secrets. Edited by scripts/access.sh (add-admin, add-host, remove-host);\n"
          "# comments here are not preserved. Which secret each host needs comes from its tags.\n")
GEN_HEADER = ("# GENERATED by scripts/access.sh sync from config/access.yml, config/inventory/hosts.yml\n"
              "# and the tag manifests. Do not edit; edit those and re-run sync.\n")
AGE_RE = re.compile(r"^age1[0-9a-z]{50,}$")


def load(path, default):
    if not os.path.exists(path):
        return default
    with open(path) as fh:
        return yaml.safe_load(fh) or default


def save_access(data):
    with open(ACCESS, "w") as fh:
        fh.write(HEADER)
        yaml.safe_dump(data, fh, sort_keys=True, default_flow_style=False)


def framework_dir(access):
    d = os.environ.get("CONSIGLIERE_DIR") or access.get("framework_dir") or "../consigliere"
    d = d if os.path.isabs(d) else os.path.normpath(os.path.join(ROOT, d))
    if not os.path.isfile(os.path.join(d, "hosts", "roles", "fleet_plan", "lookup_plugins", "fleet_roles.py")):
        sys.exit(f"ERROR: framework checkout not found at {d}. Set CONSIGLIERE_DIR or framework_dir in config/access.yml.")
    return d


def resolver(fw):
    path = os.path.join(fw, "hosts", "roles", "fleet_plan", "lookup_plugins", "fleet_roles.py")
    spec = importlib.util.spec_from_file_location("fleet_roles", path)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod.resolve


def needs(access):
    """host -> set of secret scopes its tags need."""
    fw = framework_dir(access)
    resolve = resolver(fw)
    allvars = load(os.path.join(ROOT, "config", "vars", "group", "all.yml"), {})
    dims = allvars.get("fleet_tag_dimensions", ["util", "feat", "cert", "prop"])
    dirs = [os.path.join(ROOT, "config", "tags"), os.path.join(fw, "hosts", "tags")]
    hosts = (load(HOSTS, {}).get("all", {}) or {}).get("hosts", {}) or {}
    out = {}
    for name, vals in hosts.items():
        out[name] = set(resolve(vals or {}, dims, dirs)["secrets"])
    return out


def scope_file(scope):
    kind, _, name = scope.partition(".")
    return f"config/secrets/{kind}/{name}.yml"


def existing_scopes():
    out = []
    for p in glob.glob(os.path.join(ROOT, "config", "secrets", "*", "*.yml")):
        kind = os.path.basename(os.path.dirname(p))
        out.append(f"{kind}.{os.path.basename(p)[:-4]}")
    return out


def compute(access):
    admins = access.get("admins", {}) or {}
    hostkeys = access.get("hosts", {}) or {}
    extra = access.get("extra_grants", {}) or {}
    need = needs(access)
    readers = {}
    for host, scopes in need.items():
        for sc in scopes:
            readers.setdefault(sc, set()).add(host)
    for sc, hs in extra.items():
        readers.setdefault(sc, set()).update(hs)
    for sc in existing_scopes():
        readers.setdefault(sc, set())
    warnings = []
    rules = []
    for sc in sorted(readers):
        keys = set(admins.values())
        for h in sorted(readers[sc]):
            if h in hostkeys:
                keys.add(hostkeys[h])
            else:
                warnings.append(f"host {h} needs {sc} but has no age key registered (scripts/access.sh add-host {h} <key>)")
        if not keys:
            warnings.append(f"{sc}: no admin or host keys at all (scripts/secrets.sh init-admin)")
            continue
        rules.append({"path_regex": "^" + re.escape(scope_file(sc)) + "$", "age": ",".join(sorted(keys))})
    return rules, readers, need, warnings


def render(rules):
    return GEN_HEADER + yaml.safe_dump({"creation_rules": rules}, sort_keys=False, default_flow_style=False)


def cmd_show(access):
    rules, readers, need, warnings = compute(access)
    hostkeys = access.get("hosts", {}) or {}
    print("Admins:", ", ".join(sorted((access.get("admins") or {}))) or "(none: run scripts/secrets.sh init-admin)")
    print("\nHosts (from hosts.yml):")
    for h in sorted(need):
        print(f"  {h:20} key {'registered' if h in hostkeys else 'MISSING':10} needs: {', '.join(sorted(need[h])) or '-'}")
    print("\nSecrets and who can read them (besides admins):")
    for sc in sorted(readers):
        print(f"  {sc:24} {', '.join(sorted(readers[sc])) or '-'}   [{'exists' if os.path.exists(os.path.join(ROOT, scope_file(sc))) else 'not created'}]")
    for w in warnings:
        print("WARN:", w, file=sys.stderr)


def is_sops(path):
    with open(path) as fh:
        return any(line.startswith("sops:") for line in fh)


def cmd_sync(access, update=True, check=False):
    rules, readers, need, warnings = compute(access)
    text = render(rules)
    for w in warnings:
        print("WARN:", w, file=sys.stderr)
    if check:
        cur = open(SOPS_YAML).read() if os.path.exists(SOPS_YAML) else ""
        if cur != text:
            print(".sops.yaml is out of date: run scripts/access.sh sync", file=sys.stderr)
            return 1
        return 0
    with open(SOPS_YAML, "w") as fh:
        fh.write(text)
    print(f"Wrote .sops.yaml ({len(rules)} rule(s))")
    if update:
        for sc in sorted(readers):
            p = os.path.join(ROOT, scope_file(sc))
            if os.path.exists(p) and is_sops(p):
                r = subprocess.run(["sops", "updatekeys", "-y", p], cwd=ROOT, capture_output=True, text=True)
                print(("updated  " if r.returncode == 0 else "FAILED   ") + scope_file(sc))
                if r.returncode != 0:
                    print("   " + (r.stderr.strip().splitlines() or ["?"])[-1], file=sys.stderr)
                    return 1
    return 0


def main(argv):
    if not argv:
        print(__doc__)
        return 2
    access = load(ACCESS, {})
    cmd = argv[0]
    if cmd in ("add-admin", "add-host"):
        if len(argv) != 3 or not AGE_RE.match(argv[2]):
            sys.exit(f"usage: access.sh {cmd} <name> <age public key (age1...)>")
        access.setdefault("admins" if cmd == "add-admin" else "hosts", {})[argv[1]] = argv[2]
        save_access(access)
        print(f"Registered {argv[1]}. Next: scripts/access.sh sync")
        return 0
    if cmd == "remove-host":
        (access.get("hosts") or {}).pop(argv[1], None)
        save_access(access)
        print(f"Removed {argv[1]}. Next: scripts/access.sh sync, then ROTATE the secrets it could read (it has seen them).")
        return 0
    if cmd == "show":
        cmd_show(access)
        return 0
    if cmd == "sync":
        return cmd_sync(access, update="--no-update" not in argv, check="--check" in argv)
    print(__doc__)
    return 2


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
